/* Copyright 2013 ARM Limited. All rights reserved. */
#ifndef PVVERSION_H
#define PVVERSION_H
#define SYSGEN_PVMODELLIB_MAJOR 8
#define SYSGEN_PVMODELLIB_MINOR 1
#define SYSGEN_PVMODELLIB_BUILD 37
#define SYSGEN_PVMODELLIB_VER_STR "8.1"
#define SYSGEN_PVMODELLIB_MAJOR_STR "8"
#define SYSGEN_PVMODELLIB_MINOR_STR "1"
#define SYSGEN_PVMODELLIB_BUILD_STR "37"
#endif
